{% set name = "jupyter-sphinx" %}
{% set package = "jupyter_sphinx" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ package }}-{{ version }}.tar.gz
  sha256: 2e23699a3a1cf5db31b10981da5aa32606ee730f6b73a844d1e76d800756af56

build:
  number: 2
  noarch: python

outputs:
  - name: jupyter-sphinx
    script: {{ PYTHON }} -m pip install . -vv
    requirements:
      host:
        - pip
        - python >=3.6
        - hatchling
      run:
        - python >=3.6
        - ipython
        - ipywidgets >=7.0.0
        - nbconvert >=5.5
        - nbformat
        - sphinx >=2
    test:
      imports:
        - jupyter_sphinx

  - name: jupyter_sphinx
    build: 
      noarch: generic
      run: 
        - {{ pin_subpackage('jupyter-sphinx', max_pin="x.x.x") }}
    test:
      imports:
        - jupyter_sphinx

about:
  home: https://github.com/jupyter/jupyter-sphinx/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sphinx extension for rendering of Jupyter interactive widgets.
  doc_url: https://jupyter-sphinx.readthedocs.io/

extra:
  recipe-maintainers:
    - akhmerov
    - chrisjsewell
    - 12rambau
